print("DABDBADDDDDAAAAFTFTDCFTFBAAFTFDDABBDABBBCBB")
# DABCA AADDD CAABC FTTFA CTTFB DBTFF ABCBB AACBD BBC
     **  *    *  **   ***  *  * ****  ***   * * * * *
  DABDB ADDDD DAAAD FTFTD CFTFB AAFTF DDABB DABBB CBB